### ISSUE TITLE
Open Cue and ellipsis buttons do not do anything

### ISSUE THREAD

**Issue by mjb2010** [hdijkema/pcutmp3-gui#4]
I used the Windows installer on my Win7 64-bit system. File > Open Cue does not do anything. The "..." button does not do anything, either.

**Comment by mjb2010** [comment]
Apparently this was fixed by pull request #3 . Will you accept the change?

**Comment by hdijkema** [comment]
Hope it's oke now.

**Comment by mjb2010** [comment]
Can you make a new Windows installer?
